services:
  postgres:
    image: postgres:16-alpine
    container_name: prayer-rule-db
    environment:
      POSTGRES_USER: prayerrule
      POSTGRES_PASSWORD: prayerrule_dev_password
      POSTGRES_DB: prayerrule
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prayerrule"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prayer-rule-app
    environment:
      DATABASE_URL: postgresql://prayerrule:prayerrule_dev_password@postgres:5432/prayerrule
      PORT: 5000
      NODE_ENV: production
    ports:
      - "3000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
